### PR TITLE
bump php version and cleanup code

### LINKED ISSUE #177: No Deprication

### PR DESCRIPTION
**Pull request by dbu**
fix #177

### CODE REVIEW

**Comment by wouterj** [comment]
Both todo items should not be done. We have to support CMF 1.x for a while (up to the date Symfony 2.8 reached eom). Updating all code to short array and ::class will make merging difficult.

**Comment by dbu** [comment]
i am not sure we want to maintain the 1.x versions until november 2018... but both of these changes are not urgent nor any kind of BC break, so i won't do them yet.

**Comment by dbu** [comment]
i adjusted the build matrix to drop php 5.4 and 5.3. good to merge?

**Comment by dbu** [comment]
sure, will do when merged.

**Comment by wouterj** [comment]
Fyi, due to the renaming of `Tests` to `tests`, no tests were executed by Travis. This PR introduced some failures, which I fixed in https://github.com/symfony-cmf/routing/commit/0aa8838b01778dc6ca46e26e886e22422078fe0e

**Comment by dbu** [comment]
uups. thanks for noting and fixing!

**Pull request merged**
