### PR TITLE
Support Symfony 4.

### PR DESCRIPTION
**Pull request by derrabus**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Fixed tickets | none
| License       | MIT
| Doc PR        | N/A

This PR adds Symfony 4 to the composer.json file. The tests passed without modification. However, the library pulls dependencies that still depend on Symfony 3.x.

#SymfonyConHackday2017

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
cool, looks good, but the build (currently allowed to fail) for symfony 4 is broken:
https://travis-ci.org/symfony-cmf/Routing/jobs/303915410
Reason:
https://github.com/doctrine/DoctrinePHPCRBundle/pull/292
and 
https://github.com/symfony-cmf/testing/pull/155
need to become green.
Testing is blocked by fos/jsrouting and doctrine/phpcr-bundle needs some love and a green testing commit.

**Comment by ElectricMaxxx** [comment]
But when those two PRs allows symfony 4.0 CMF at all is ready for 4.0, cause 3.4 deprecations are almost gone, see: https://github.com/symfony-cmf/symfony-cmf/issues/254

**Comment by ElectricMaxxx** [comment]
yes ... it is red :-)

**Comment by dbu** [comment]
this has been wrapped up in another MR. thanks for getting it started @derrabus

**Pull request closed without merging**
