### PR TITLE
remove Symfony 4.3 event dispatcher deprecation messages

### PR DESCRIPTION
**Pull request by jkabat**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | fixed
| License       | MIT

### CODE REVIEW

**Comment by dbu** [comment]
hi, thanks for this one! can you please rebase on master to (hopefully) get the build fixed?

**Comment by jkabat** [comment]
@dbu rebased

**Comment by dbu** [comment]
cheers!

**Comment by jkabat** [comment]
@dbu somehow this is still not tagged... why it was skipped from the latest release?

**Comment by dbu** [comment]
i was waiting for symfony 5 support in #245, but its complicated. i will do a patch relese with this now

**Comment by dbu** [comment]
https://github.com/symfony-cmf/Routing/releases/tag/2.2.0

**Pull request merged**
