### PR TITLE
ChainRouter: propagate match() call instead of mocking Request and calling matchRequest()

### PR DESCRIPTION
**Pull request by sustmi**
Deprecates PR https://github.com/symfony-cmf/Routing/pull/147

### CODE REVIEW

**Comment by dbu** [comment]
thanks for this pull request. i am however afraid that this could lead to unexpected behaviour changes. see for example #151. 

@sustmi @ pk16011990 is the problem you encounter not solved when you use the matchRequest method with a request that you create correctly?

**Comment by sustmi** [comment]
@dbu , OK lets forget about fixing propagating ```match()```.
Still, I insist that the bug is in ```ChainRouter``` and not Symfony.

```UrlMatcherInterface::match()``` takes pathinfo as parameter and not URL.
You should not pass pathinfo into ```Request::create()```, because it expects URI.
According to [RFC-3986](http://tools.ietf.org/html/rfc3986#section-5.4.1) URI ```//g``` means ```g``` is hostname ie. pathinfo is ```/```.

```Request::create()``` is correct, but ```ChainRouter``` is not using it right.

These commits try to fix the behaviour: https://github.com/sustmi/Routing/compare/master...fix-matching-pathinfo?expand=1

**Comment by lsmith77** [comment]
maybe a safer approach would be to set a "dummy host" in this edge case to prevent the ``//`` being misinterpreted?

**Comment by dbu** [comment]
@sustmi okay, sorry for letting this sit around so long. i propose we add handling for the specific case of path starting with `//` and in that case add //host from $_REQUEST if set, //localhost otherwise. that should avoid the edge case, right? can you do a pull request @sustmi ?

**Comment by sustmi** [comment]
I don't understand. If you have Request instance, you don't have to fake it. Or do you really mean $_REQUEST superglobal?

**Comment by dbu** [comment]
i do mean the superglobal. we can also go for always localhost. its just
for the edge case of //. we have to rethink this for 2.0 but in 1.x i dont
want to change this behaviour so fundamentally. hopefully "match(path)"
wont exist anymore for 2.0 (symfony 3)

**Comment by dbu** [comment]
superseeded by #163

**Pull request closed without merging**
